name: Test Nextcloud App
on:
    push:
        branches:
            - main
        paths:
            - 'lib/**'
            - 'templates/**'
    workflow_dispatch:
jobs:
    php:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        
        steps:
            - name: checkout repository 
              uses: actions/checkout@v7
            
            - name: PHP syntax check
              run: |
                    find . -name "*.php" -print0 | xargs -0 -n1 php -l